version: 1
formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(message)s'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: logs/etl_pipeline.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  console:
    class: logging.StreamHandler
    formatter: json
loggers:
  etl_pipeline:
    level: INFO
    handlers: [file, console]
    propagate: false
root:
  level: WARNING
  handlers: [console]