version: 1
formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '{"asctime": "%(asctime)s", "levelname": "%(levelname)s", "name": "%(name)s", "filename": "%(filename)s", "lineno": %(lineno)d, "message": "%(message)s", %(extra)s}'
handlers:
  file:
    class: logging.FileHandler
    filename: C:/projects/etl_pipeline/logs/etl_pipeline.log
    formatter: json
    level: DEBUG
  console:
    class: logging.StreamHandler
    formatter: json
    level: DEBUG
loggers:
  etl_pipeline:
    level: DEBUG
    handlers: [file, console]
    propagate: false