database:
  type: mysql
  host: localhost
  port: 3306
  user: root
  password: Letmein123$
  database: dev_db

logging:
  level: INFO
  file: "logs/pipeline.log"

paths:
  inbox: "data/raw"
  processed: "data/processed"
  failed: "data/failed"
  archive: "data/archive"

column_mapping:
  מס_לקוח: customer_id
  תז: customer_id
  שם_לקוח: customer_name
  שם: customer_name
  דמי_חודש: fees
  סכום: fees

required_columns:
  - id
  - first_name
  - last_name
  - name
  - fee

validation:
  id_sample_size: 5

data_prep:
  steps:
    - isolate_table
    - identify_id
    - identify_provider
    - find_date
    - identify_fee
  issue_threshold: 1
  fee_values: [62, 30]
  fee_outlier_threshold: 10
  date_formats: ['%d-%m-%Y', '%d/%m/%Y', '%Y%m%d', '%m-%d-%Y', '%m/%d/%Y', '%b-%Y']
  cutoff_day: 5
  providers:
    'ספק א': 'ספק_א'
    'ספק ב': 'ספק_ב'
    'ספק ג': 'ספק_ג'