database:
  type: mysql
  host: localhost
  port: 3306
  user: root
  password: Letmein123$
  database: dev_db

logging:
  level: INFO
  file: "logs/pipeline.log"

paths:
  inbox: "data/raw"
  processed: "data/processed"
  failed: "data/failed"
  archive: "data/archive"

column_mapping:
  מס_לקוח: customer_id
  תז: customer_id
  שם_לקוח: customer_name
  שם: customer_name
  דמי_חודש: fees
  סכום: fees

required_columns:
  - id
  - first_name
  - last_name
  - name
  - fee

ingestion:
  skip_reports_insert: true

validation:
  id_sample_size: 5
  date_column_threshold: 0.7
  issue_threshold: 2
  non_null_threshold: 0.5  # Fraction of non-null values to identify data row
  header_patterns: ['מס_לקוח', 'תז', 'שם', 'דמי', 'סכום']

data_prep:
  steps:
    - isolate_table
    - identify_id
    - truncate_summary_rows
    - identify_provider
    - find_date
    - identify_fee
  issue_threshold: 1
  fee_outlier_threshold: 10
  date_formats: ['%d-%m-%Y', '%d/%m/%Y', '%Y%m%d', '%m-%d-%Y', '%m/%d/%Y', '%b-%Y']
  cutoff_day: 5
  providers:
    'ספק א': 'ספק_א'
    'ספק ב': 'ספק_ב'
    'ספק ג': 'ספק_ג'
  id_columns: ['id', 'customer_id', 'מס_לקוח', 'תז']
  fee_columns: ['fee', 'amount', 'cost', 'דמי', 'סכום']
  mandatory_columns: ['customer_id', 'fee', 'provider', 'paid_month']
  row_validation_rules:
    fee_values: [62, 30]
    provider_reject: ['unknown']
